config/routes.rb
Rails.application.routes.draw do
  #update registration controller
  #devise_for :users, :controllers => { registration: 'registration' }
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'site#index'

  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'
  get 'about'   => 'site#about'


  #post 'profile' => 'profile#create' #if you come with POST request, go to create
  #get 'profile' => 'profile#show' # if you come with GET request, go to index

  get 'guides' => 'guides#index' #show list of guides
  get 'guides/:location' => 'guides#index'
  post 'guides/comment/:user_id' => 'guides#comment'
  get 'guides/id/:id' => 'guides#show'
  post 'guides/newlanguage' => 'guides#newlanguage'
  post 'guides/newlocation' => 'guides#newlocation'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :city
  after_validation :geocode
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  validates :surname, presence: true
  validates :firstname, presence: true
  validates :description, presence: true
  has_and_belongs_to_many :languages
  has_many :comments
  belongs_to :location

  has_attached_file :avatar, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_current_user

  def set_current_user
    User.current = current_user
  end
#  def self.save(upload)
#    name = upload['datafile'].original_filename
#    directory = "public/data"
#    path = Guides.join(directory, name)
#    Guides.open(path, "wb") { |f| f.write(upload['datafile'].read)}
#  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  protect_from_forgery with: :null_session,  :except => [:comment]

  def index #listing of the following items either with a location variable or not

    if params[:location].blank?
      @guides = User.where(isguide: true)
    else
      @guides = (Location.find_by city: params[:location]).users.where(isguide: true)

    end
  end


  def show #show profile
    user_id  = params[:id]
    commenter_id = params[:commenter_id]
    @profile = User.find(user_id)

    if user_id.blank?
      @post = Comment.all
    else
      @post = Comment.where(user_id: user_id)

    end
  end

  def newlocation #create new location
    newcity = params[:locality].capitalize
    a = Location.find_by city: newcity
    if a.nil? == true
      newlocation = Location.new
      newlocation.city = newcity
      if newlocation.save
        flash.now[:notice] = "Location added"
      else
        flash.now[:notice] = "Location add failed"
      end
    else
      flash[:notice] = "Location exists"
    end
    redirect_to :back
  end

  def newlanguage
    language = params[:language]
    @languages = Language.find_by language: language

    if @languages.nil? == true
      newlanguage = Language.new
      newlanguage.language = language.capitalize
      if newlanguage.save
        flash.now[:notice] = "Language added"
      else
        flash.now[:notice] = "Language add failed"
      end
    else
      flash[:notice] = "Language exists"
    end
    redirect_to :back
  end


  def comment
    if user_signed_in?
      user_id = params[:user_id]
      comments = Comment.new
      comments.title = params[:title]
      comments.content = params[:content]
      comments.user_id = user_id
      comments.rating = params[:rating]
      comments.commenter_id = User.current.id

      if comments.save == false
        flash.now[:notice] = "Sorry there was an error"
      end
      redirect_to :back
    end
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create

    @locations = Location.all
    super

    language_ids = params[:user][:language_ids] #grab IDS
    language_ids.each do |id|
      @user.languages << Language.find(id) unless id.blank?

    end
  end

  def update
    super

    language_ids = params[:user][:language_ids] #grab IDS
    language_ids.each do |id|
      @user.languages << Language.find(id) unless id.blank?
    end
  end

  def new
    @locations = Location.all
    super
  end


  private


  def sign_up_params
    @languages = Language.all

    params.require(:user).permit(:firstname, :surname, :location_id, :isguide, :description, :email, :avatar, :password, :password_confirmation, :languages )
  end

  def account_update_params
    params.require(:user).permit(:firstname, :surname, :location_id, :isguide, :description, :email, :avatar, :password, :password_confirmation, :current_password, :languages )
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index #listing of the following items

    @locations = Location.all
    @locations_guides_images = []

    # Only 4 guides are to be shown in the map box at a time
    # the following function randomizes the photos of guides that appear in the map box
    @locations.each do |location_id| #loop through guides in each location
      guide_loc = User.where(isguide: true, location_id: location_id)

      if guide_loc.length > 4
        rnd = (0..(guide_loc.length - 1) ).to_a.shuffle #shuffle number indexes
        rnd = rnd.take(4)
        for index in rnd
          @locations_guides_images << guide_loc[index]
        end
      elsif guide_loc.length > 0
        for index in 0..(guide_loc.length - 1)
          @locations_guides_images << guide_loc[index]
        end
      end
    end



  end


  def privacy #static page
  end

  def terms
  end

  def about
  #     flash.now[:alert] = "About"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

  def flash_noty_script_tag
    unless flash.empty?
      noties = flash.map do |name, message|
        if message.is_a?(String) || message.is_a?(ActiveModel::Errors)
          type = ( name == :notice ? "success" : "error" )
          timeout = ( name == :notice ? 4000 : 30000 )
          text = ( message.is_a?(ActiveModel::Errors) ? "It's an error object" : message )

          "noty({ layout: 'top', type: '" + type +
          "', timeout: " + timeout.to_s +
          ", text: \"" + text +
          "\"});"
        end
      end
      # binding.pry
      # javascript_tag( "$(function() { \n  " + noties.join("\n  ") + "\n}); debugger();")
      javascript_tag(noties.join("\n "));
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tours</title>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?language=en"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<script type="text/javascript">

  idFunction = function(id) {
    $("#user_location_id").val(id);
    return true
  };

</script>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">FindALocal</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <li class="active"><%= nav_link 'List Guides', guides_path %></li>
          <li><%= nav_link 'About', about_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><div class="logged in"><%= current_user.email %></div></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
          <% else %>


            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>


    <div class="container_bg">
  <div class="container">

    <%= yield %>
    </div>

  </div>


<%= flash_noty_script_tag %>
<div class="foot"></div>
</body>
</html>